# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20181120_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='full_name',
        ),
    ]
