# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20181120_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line2',
            new_name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
