# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_urlfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
