# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180926_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='path',
            field=models.TextField(default='', max_length=200),
        ),
    ]
