# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagetwo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
