# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181017_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='productimg',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
