# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photog',
            field=models.CharField(default='', max_length=200),
        ),
    ]
