# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_photog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photog',
        ),
    ]
